name: RealCarry
version: 1.1
main: com.nonkungch.realcarry.RealCarry
api-version: 1.21
author: NonKungCh
description: A plugin that lets you carry mobs and blocks on your head.
permissions:
  realcarry.carry.mob:
    description: Allows players to carry mobs.
    default: true
  realcarry.carry.block:
_permission_:
    description: Allows players to carry blocks.
    default: true
    
