name: RealCarry
version: 4.2.0
main: com.nonkungch.realcarry.RealCarry # <--- แก้ไข
api-version: 1.21 
author: NonKungCh # <--- แก้ไข
commands:
  rc:
    description: คำสั่งหลักของ RealCarry
    usage: /<command> [help|reload]
    aliases: [realcarry]
permissions:
  realcarry.use:
    description: อนุญาตให้ใช้ความสามารถในการอุ้ม
    default: true
  realcarry.reload:
    description: อนุญาตให้ใช้ /rc reload
    default: op
