name: RealCarry
version: 3.8
main: com.nonkungch.realcarry.RealCarry
api-version: 1.21
author: NonKungCh
description: A plugin that lets you carry mobs and blocks on your head.

commands:
  realcarry:
    description: Main command for RealCarry.
    usage: /<command> [reload]
    aliases: [rc]

permissions:
  realcarry.reload:
    description: Allows reloading the plugin's configuration.
    default: op
  # --- เพิ่ม Permission นี้ ---
  realcarry.carry.player:
    description: Allows the player to carry other players.
    default: false
  # (เราไม่จำเป็นต้องมี realcarry.carry.entity หรือ block ที่นี่แล้ว
  # เพราะโค้ดล่าสุดคือทุกคนอุ้มได้ แต่เราจะเพิ่มมันกลับเข้าไปในโค้ด)
  # (แก้ไข: ผมจะเพิ่มกลับเข้าไปให้ตามโค้ดต้นฉบับของคุณ แต่ลบ ! ออก)
  realcarry.carry.entity:
    description: Allows the player to carry entities.
    default: true # หรือ false ถ้าอยากให้ต้องมี perm
  realcarry.carry.block:
    description: Allows the player to carry blocks.
    default: true # หรือ false ถ้าอยากให้ต้องมี perm
    
