name: RealCarry
version: 3.0
main: com.nonkungch.realcarry.RealCarry
api-version: 1.21
author: NonKungCh
description: A plugin that lets you carry mobs and blocks on your head.

# --- เพิ่มส่วนนี้เข้าไป ---
commands:
  realcarry:
    description: Main command for RealCarry.
    usage: /<command> [reload]
    aliases: [rc]

permissions:
  realcarry.reload:
    description: Allows reloading the plugin's configuration.
    default: op
# -------------------------
